[package]
name = "tutorial"
version = "0.1.0"
authors = ["Vladimir Nikitenko <wx282@rambler.ru>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
